### ISSUE TITLE
AttributeError: test_init (test.test_fitsimage.FITSImageTest)

### ISSUE THREAD

**Issue by jorgegocre** [vterron/lemon#56] opened 2015-05-04 12:49 UTC
I have this error running the tests

    ...
    test_init (test.test_fitsimage.FITSImageTest) ... ERROR

    ======================================================================
    ERROR: test_init (test.test_fitsimage.FITSImageTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
       File
    "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/test/test_fitsimage.py",
    line 169, in test_init
         FITSImage(nonstandard_path)
       File "/mnt/EMC/Optcesga_SVG/opt/cesga/lemon-0.2.0/fitsimage.py", line
    124, in __init__
         self.size = handler[0].data.shape[::-1]
    AttributeError: 'NoneType' object has no attribute 'shape'

    ----------------------------------------------------------------------
    Ran 88 tests in 2113.003s

    FAILED (errors=1)

**Comment by vterron** [comment] 2015-05-05 12:26
What's the output of the following command?
      
    python -c "import pyfits; print pyfits.__version__"

Is it 3.3+, by any chance?

**Comment by jorgegocre** [comment] 2015-05-06 10:01
Yes,3.3

**Comment by vterron** [comment] 2015-05-25 10:21
Fixed in 847cf05. The error was caused by [a change introduced in PyFITS 3.3](https://github.com/spacetelescope/PyFITS/issues/94), which now deals with non-standard FITS files differently. Thanks so much for reporting this!

**Closed by vterron** 2015-05-25 10:21 UTC
Labels: bug
